# Generated by Django 4.1.7 on 2023-04-05 18:01

import Product.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("first_name", models.CharField(default="", max_length=30)),
                ("last_name", models.CharField(default="", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("tax_ID", models.IntegerField(default=0)),
                ("home_address", models.TextField()),
                ("role", models.CharField(default="customer", max_length=100)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", Product.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
                ("warranty_status", models.CharField(max_length=100)),
                ("distributor_info", models.TextField()),
                ("order_number", models.CharField(max_length=100)),
                ("delivery_address", models.TextField()),
                (
                    "order_process_status",
                    models.CharField(default="processing", max_length=100),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InStockProduct",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="Product/static/img/")),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                ("quantity_in_stocks", models.IntegerField()),
                ("price", models.FloatField(default=0)),
                ("warranty_status", models.CharField(max_length=100)),
                ("distributor_info", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Product.category",
                    ),
                ),
            ],
        ),
    ]
