# Generated by Django 4.1.7 on 2023-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_users_home_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
