# Generated by Django 4.1.7 on 2023-04-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_alter_users_first_name_alter_users_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instockproduct",
            name="image",
            field=models.ImageField(upload_to="product_images"),
        ),
    ]
