# Generated by Django 4.1.7 on 2023-04-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0006_comment_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedproduct",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
