# Generated by Django 4.1.7 on 2023-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_users_first_name_alter_users_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
