# Generated by Django 4.1.7 on 2023-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_orderedproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
