# Generated by Django 4.1.7 on 2023-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_orderedproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='instockproduct',
            name='discount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
