# Generated by Django 4.1.7 on 2023-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_instockproduct_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='purchased_price',
            field=models.IntegerField(default=0),
        ),
    ]
