# Generated by Django 4.1.7 on 2023-06-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_orderedproduct_instockid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('warranty_status', models.CharField(max_length=100)),
                ('distributor_info', models.TextField()),
                ('quantity', models.IntegerField()),
                ('purchased_price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
