# Generated by Django 4.1.7 on 2023-05-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_orderedproduct_quantity'),
        ('Cart', '0002_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='Product.instockproduct'),
        ),
    ]
