# Generated by Django 4.1.7 on 2023-05-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_purchasehistory_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name_plural': 'Purchase Histories'},
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='id',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('purchased_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='Cart.purchasehistory')),
            ],
            options={
                'verbose_name_plural': 'Refunds',
            },
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
