# Generated by Django 4.1.7 on 2023-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_purchasehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='refund_accepted',
            field=models.BooleanField(default=False, verbose_name='Refund Accepted'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='Refund Requested'),
        ),
    ]
