# Generated by Django 4.1.7 on 2023-05-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_purchasehistory_refund_accepted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
