# Generated by Django 4.1.7 on 2023-05-27 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_orderedproduct_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0006_delete_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('ID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='Product.instockproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Refunds',
            },
        ),
    ]
