# Generated by Django 4.1.7 on 2023-04-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnonUser",
        ),
    ]
